version: '2.1'
networks:
  default:
    external:
      name: managed_container_nw
services:
  server:
    image: rsundahl/server:latest
    links:
      - api
    ports:
      - "8780:8780"
  api:
    image: rsundahl/api:latest
    ports:
      - "8781:8781"
# wrapper:
##  privileged: true
#   image: polyverse-store.jfrog.io/standalone-base:latest
#   environment:
#     - "SA_POLYVERSE_ID=pvdind"
#     - "SA_POLYVERSE_ROUTER_HTTP_PORT=8782"
#     - "SA_POLYVERSE_API_DISABLE=true"
#     - "SA_APP_NAME=DinD-APP"
#     - "SA_APP_HTTP_PORT=8780"
#   command: ["rsundahl/server:latest"]
#   links:
#     - api
##  ports:
##    - "8782:8782"
#   volumes:
#     - ~/.docker/config.json:/root/.docker/config.json
#     - /var/run/docker.sock:/var/run/docker.sock
##    - /var/run/docker.sock:/var/run/outer_docker.sock
##    - /lib/modules:/lib/modules
  wrapper2:
    image: polyverse-tools.jfrog.io/polyverse:0d25792e58801e8815be33c3d3f7c89d081bcfcd
    command: ["wrap", "rsundahl/api:latest"]
    ports:
      - "8783:8781"
    volumes:
      - ~/.docker/config.json:/root/config.json
      - /var/run/docker.sock:/var/run/docker.sock
